In [ ]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv(r"D:\Bluestock\Project\Data\Raw\07_scheme_performance.csv")

In [4]:
df.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low


In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   amfi_code           40 non-null     int64  
 1   scheme_name         40 non-null     str    
 2   fund_house          40 non-null     str    
 3   category            40 non-null     str    
 4   plan                40 non-null     str    
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64  
 16  expense_ratio_pct   4

In [25]:
non_numeric = pd.to_numeric(df["return_1yr_pct"], errors="coerce").isna()
non_numeric.unique()

array([False])

In [28]:
validate_3yr = pd.to_numeric(df["return_3yr_pct"],errors="coerce").isna()
validate_3yr.unique()

array([False])

In [ ]:
validate_5yr=pd.to_numeric(df["return_5yr_pct"],errors="coerce").isna()
validate_5yr.unique()

array([False])

In [32]:
(df["sharpe_ratio"]<=0).sum()

np.int64(0)

In [45]:
df["expense_ratio_pct"].head(20)

0     1.54
1     0.66
2     1.43
3     0.72
4     0.77
5     1.55
6     0.92
7     1.38
8     0.78
9     0.56
10    1.42
11    0.80
12    1.36
13    1.41
14    0.74
15    1.51
16    0.72
17    1.53
18    0.89
19    0.55
Name: expense_ratio_pct, dtype: float64

In [49]:
for n in df["expense_ratio_pct"]:
    if n<0.1 or n>2.5:
        print(n)

In [50]:
df.to_csv("clean_performance.csv",index=False)